apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.front.name }}-service"
spec:
  selector:
    app: {{ .Values.front.name }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.front.service.port }}
      targetPort: http
