apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.front.name }}"
spec:
  tls:
  - hosts:
    - {{ .Values.front.host }}
  rules:
    - host: {{ .Values.front.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.front.name }}-service"
                port:
                  name: http
