apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.front.name }}-deployment"
  labels:
    app: {{ .Values.front.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.front.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.front.name }}
    spec:
      containers:
      - name: {{ .Values.front.name }}
        image: {{ .Values.front.image }}
        ports:
        - containerPort: {{ .Values.front.containerPort }}
          name: http
